-- Add foreign key(s) to TRAVELS_TO table.
ALTER TABLE TRAVELS_TO ADD CONSTRAINT TRAVELS_TO_FK1 FOREIGN KEY (USERNAME)
REFERENCES `MEMBER` (USERNAME)
ON DELETE CASCADE
ON UPDATE CASCADE;
    
ALTER TABLE TRAVELS_TO ADD CONSTRAINT TRAVELS_TO_FK2 FOREIGN KEY (`NAME`, PHONE_NUMBER)
REFERENCES TRAVEL_ATTRACTION (`NAME`, PHONE_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to RATES_ATTRACTION_MEMBER table.
ALTER TABLE RATES_ATTRACTION_MEMBER ADD CONSTRAINT RATES_ATTRACTION_MEMBER_FK1 FOREIGN KEY (USERNAME)
REFERENCES `MEMBER` (USERNAME)
ON DELETE CASCADE
ON UPDATE CASCADE;
    
ALTER TABLE RATES_ATTRACTION_MEMBER ADD CONSTRAINT RATES_ATTRACTION_MEMBER_FK2 FOREIGN KEY (`NAME`, PHONE_NUMBER)
REFERENCES TRAVEL_ATTRACTION (`NAME`, PHONE_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to EDITS table.
ALTER TABLE EDITS ADD CONSTRAINT EDITS_FK1 FOREIGN KEY (USERNAME)
REFERENCES `MEMBER` (USERNAME)
ON DELETE CASCADE
ON UPDATE CASCADE;
    
ALTER TABLE EDITS ADD CONSTRAINT EDITS_FK2 FOREIGN KEY (`NAME`, PHONE_NUMBER)
REFERENCES TRAVEL_ATTRACTION (`NAME`, PHONE_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- Add foreign key(s) to TRAVEL_ATTRACTION table.
ALTER TABLE TRAVEL_ATTRACTION ADD CONSTRAINT TRAVEL_ATTRACTION_FK FOREIGN KEY (CITY_NAME, STATE_NAME, COUNTRY_NAME, ZIP_CODE)
REFERENCES GEOGRAPHICAL_LOCATION (CITY_NAME, STATE_NAME, COUNTRY_NAME, ZIP_CODE)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- Add foreign key(s) to SIGHT table.
ALTER TABLE SIGHT ADD CONSTRAINT SIGHT_FK FOREIGN KEY (`NAME`, PHONE_NUMBER)
REFERENCES TRAVEL_ATTRACTION (`NAME`, PHONE_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to RESTAURANT table.
ALTER TABLE RESTAURANT ADD CONSTRAINT RESTAURANT_FK1 FOREIGN KEY (`NAME`, PHONE_NUMBER)
REFERENCES TRAVEL_ATTRACTION (`NAME`, PHONE_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE;
    
ALTER TABLE RESTAURANT ADD CONSTRAINT RESTAURANT_FK2 FOREIGN KEY (BUSINESS_NAME)
REFERENCES BUSINESS_OWNER (`NAME`)
ON DELETE CASCADE
ON UPDATE CASCADE;
    
-- Add foreign key(s) to SHOPPING_MALL table.
ALTER TABLE SHOPPING_MALL ADD CONSTRAINT SHOPPING_MALL_FK1 FOREIGN KEY (`NAME`, PHONE_NUMBER)
REFERENCES TRAVEL_ATTRACTION (`NAME`, PHONE_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE SHOPPING_MALL ADD CONSTRAINT SHOPPING_MALL_FK2 FOREIGN KEY (BUSINESS_NAME)
REFERENCES BUSINESS_OWNER (`NAME`)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to COMMENT table.
ALTER TABLE `COMMENT` ADD CONSTRAINT COMMENT_FK1 FOREIGN KEY (USERNAME)
REFERENCES `MEMBER` (USERNAME)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE `COMMENT` ADD CONSTRAINT COMMENT_FK2 FOREIGN KEY (`NAME`, PHONE_NUMBER)
REFERENCES TRAVEL_ATTRACTION (`NAME`, PHONE_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- Add foreign key(s) to DISLIKES table.
ALTER TABLE DISLIKES ADD CONSTRAINT DISLIKES_FK1 FOREIGN KEY (USERNAME)
REFERENCES `MEMBER` (USERNAME)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
ALTER TABLE DISLIKES ADD CONSTRAINT DISLIKES_FK2 FOREIGN KEY (COMMENTID)
REFERENCES `COMMENT` (COMMENTID)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to LIKES table.
ALTER TABLE LIKES ADD CONSTRAINT LIKES_FK1 FOREIGN KEY (USERNAME)
REFERENCES `MEMBER` (USERNAME)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
ALTER TABLE LIKES ADD CONSTRAINT LIKES_FK2 FOREIGN KEY (COMMENTID)
REFERENCES `COMMENT` (COMMENTID)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to REPLIES table.
ALTER TABLE REPLIES ADD CONSTRAINT REPLIES_FK1 FOREIGN KEY (USERNAME)
REFERENCES `MEMBER` (USERNAME)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
ALTER TABLE REPLIES ADD CONSTRAINT REPLIES_FK2 FOREIGN KEY (COMMENTID)
REFERENCES `COMMENT` (COMMENTID)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to ASSOCIATED_STORES table.
ALTER TABLE ASSOCIATED_STORES ADD CONSTRAINT ASSOCIATED_STORES_FK FOREIGN KEY (`NAME`)
REFERENCES BUSINESS_OWNER (`NAME`)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to IMAGE table.
ALTER TABLE IMAGE ADD CONSTRAINT IMAGE_FK FOREIGN KEY (USERNAME)
REFERENCES `MEMBER` (USERNAME)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to TRIP_PLAN table.
ALTER TABLE TRIP_PLAN ADD CONSTRAINT TRIP_PLAN_FK FOREIGN KEY (USERNAME)
REFERENCES `MEMBER` (USERNAME)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to TRIP_PLAN_ATTRACTIONS table.
ALTER TABLE TRIP_PLAN_ATTRACTIONS ADD CONSTRAINT TRIP_PLAN_ATTRACTIONS_FK FOREIGN KEY (PLANID)
REFERENCES TRIP_PLAN (PLANID)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to ASSOCIATED_MEMBERS table.
ALTER TABLE ASSOCIATED_MEMBERS ADD CONSTRAINT ASSOCIATED_MEMBERS_FK FOREIGN KEY (PLANID)
REFERENCES TRIP_PLAN (PLANID)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to DEPARTURE_DATE_TIMES table.
ALTER TABLE DEPARTURE_DATE_TIMES ADD CONSTRAINT DEPARTURE_DATE_TIMES_FK FOREIGN KEY (PLANID)
REFERENCES TRIP_PLAN (PLANID)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to ARRIVAL_DATE_TIMES table.
ALTER TABLE ARRIVAL_DATE_TIMES ADD CONSTRAINT ARRIVAL_DATE_TIMES_FK FOREIGN KEY (PLANID)
REFERENCES TRIP_PLAN (PLANID)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to CONTAINS table.
ALTER TABLE `CONTAINS` ADD CONSTRAINT CONTAINS_FK1 FOREIGN KEY (PLANID)
REFERENCES TRIP_PLAN (PLANID)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
ALTER TABLE `CONTAINS` ADD CONSTRAINT CONTAINS_FK2 FOREIGN KEY (`NAME`, PHONE_NUMBER)
REFERENCES TRAVEL_ATTRACTION (`NAME`, PHONE_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
-- Add foreign key(s) to RATES_PLAN_MEMBER table.
ALTER TABLE RATES_PLAN_MEMBER ADD CONSTRAINT RATES_PLAN_MEMBER_FK1 FOREIGN KEY (PLANID)
REFERENCES TRIP_PLAN (PLANID)
ON DELETE CASCADE
ON UPDATE CASCADE;
        
ALTER TABLE RATES_PLAN_MEMBER ADD CONSTRAINT RATES_PLAN_MEMBER_FK2 FOREIGN KEY (USERNAME)
REFERENCES `MEMBER` (USERNAME)
ON DELETE CASCADE
ON UPDATE CASCADE;