CREATE SCHEMA PROJECT_DATABASE;

USE PROJECT_DATABASE;

-- CREATE MEMBER TABLE.
CREATE TABLE `MEMBER` (
USERNAME VARCHAR(50) PRIMARY KEY NOT NULL,
`PASSWORD` VARCHAR(50) NOT NULL, 
EMAIL	VARCHAR(50) NOT NULL,
RANKING INT NOT NULL,
STREET_NUMBER INT NOT NULL,
STREET_NAME VARCHAR(50) NOT NULL,
CITY VARCHAR(50) NOT NULL,
STATE VARCHAR(50) NOT NULL,
COUNTRY VARCHAR(50) NOT NULL,
ZIP_CODE INT NOT NULL,
NUMBER_OF_FOLLOWERS INT DEFAULT 0,
NUMBER_OF_PEOPLE_FOLLOWED INT DEFAULT 0,
MEMBER_TYPE VARCHAR(50) NOT NULL
);

	-- CREATE TRAVELS_TO TABLE.
	CREATE TABLE TRAVELS_TO (
	USERNAME VARCHAR(50) NOT NULL,
	`NAME` VARCHAR(50) NOT NULL,
	PHONE_NUMBER VARCHAR(50) NOT NULL,
	PRIMARY KEY (USERNAME, `NAME`, PHONE_NUMBER)
	);
	
	-- CREATE RATES_ATTRACTION_MEMBER TABLE.
    CREATE TABLE RATES_ATTRACTION_MEMBER (
	USERNAME VARCHAR(50) NOT NULL,	
	`NAME` VARCHAR(50) NOT NULL,
	PHONE_NUMBER VARCHAR(50) NOT NULL,
    PRIMARY KEY (USERNAME, `NAME`, PHONE_NUMBER)
	);
        	
	-- CREATE EDITS TABLE.
    CREATE TABLE EDITS (
	USERNAME VARCHAR(50) NOT NULL,
	`NAME` VARCHAR(50) NOT NULL,
	PHONE_NUMBER VARCHAR(50) NOT NULL,
    MODIFYING_MEMBER_ID VARCHAR(50) NOT NULL,
    MODIFIED_DATE DATE NOT NULL,
    PRIMARY KEY (USERNAME, `NAME`, PHONE_NUMBER)
	);

-- CREATE TRAVEL_ATTRACTION TABLE.
CREATE TABLE TRAVEL_ATTRACTION (
`NAME`	VARCHAR(50) NOT NULL,
PHONE_NUMBER VARCHAR(50) NOT NULL,
Open_time TIME NOT NULL,
Close_time	TIME NOT NULL,
WAYS_OF_TRAVEL VARCHAR(50) NOT NULL,
`DESCRIPTION` VARCHAR(300) NOT NULL,
RATING DECIMAL(3,1) NOT NULL,
STREET_NUMBER INT NOT NULL,
STREET_NAME VARCHAR(50) NOT NULL,
CITY_NAME VARCHAR(50) NOT NULL,
STATE_NAME VARCHAR(50) NOT NULL,
COUNTRY_NAME VARCHAR(50) NOT NULL,
ZIP_CODE INT NOT NULL,
PRIMARY KEY(`NAME`, PHONE_NUMBER)
);
	-- CREATE SIGHT TABLE.
	CREATE TABLE SIGHT (
	`NAME` VARCHAR(50) NOT NULL, 	
	PHONE_NUMBER VARCHAR(50) NOT NULL,
	TICKET_PRICE DECIMAL(12,2) DEFAULT 0,
    WEBLINK VARCHAR(50) NOT NULL,
    PRIMARY KEY(`NAME`, PHONE_NUMBER)
	);
    
    -- CREATE RESTAURANT TABLE.
    CREATE TABLE RESTAURANT (
	`NAME` VARCHAR(50) NOT NULL,	
	PHONE_NUMBER VARCHAR(50) NOT NULL,
	RESTAURANT_TYPE VARCHAR(50) NOT NULL,
    WEBLINK VARCHAR(50) NOT NULL,
    PRICE_RANGE_STARTING DECIMAL(12,2) NOT NULL,
    PRICE_RANGE_ENDING DECIMAL(12,2) NOT NULL,
    BUSINESS_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(`NAME`, PHONE_NUMBER)
	);
    
    -- CREATE SHOPPING_MALL TABLE.
    CREATE TABLE SHOPPING_MALL (
	`NAME` VARCHAR(50) NOT NULL,
	PHONE_NUMBER VARCHAR(50) NOT NULL,
	BUSINESS_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(`NAME`, PHONE_NUMBER)
	);
    
-- CREATE COMMENT TABLE.
CREATE TABLE `COMMENT` (
COMMENTID VARCHAR(50) PRIMARY KEY NOT NULL,	
POSTING_DATE DATE NOT NULL,
CONTENT	VARCHAR(265) NOT NULL,
POSTING_TIME TIME NOT NULL,
RATING DECIMAL(3,1) NOT NULL,
USERNAME VARCHAR(50) NOT NULL,
`NAME` VARCHAR(50) NOT NULL,
PHONE_NUMBER VARCHAR(50) NOT NULL
);
	-- CREATE DISLIKES TABLE.
	CREATE TABLE DISLIKES (
	USERNAME VARCHAR(50) NOT NULL,
	COMMENTID VARCHAR(50) NOT NULL,
    PRIMARY KEY(USERNAME, COMMENTID)
	);
    
    -- CREATE LIKES TABLE.
    CREATE TABLE LIKES (
	USERNAME VARCHAR(50) NOT NULL,
	COMMENTID VARCHAR(50) NOT NULL,
    PRIMARY KEY(USERNAME, COMMENTID)
	);
    
	-- CREATE REPLIES TABLE.
	CREATE TABLE REPLIES (
	USERNAME VARCHAR(50) NOT NULL,
	COMMENTID VARCHAR(50) NOT NULL,
    CONTENT VARCHAR(265) NOT NULL,
    PRIMARY KEY(USERNAME, COMMENTID)
	);
    
-- CREATE BUSINESS_OWNER TABLE.
CREATE TABLE BUSINESS_OWNER (
`NAME` VARCHAR(50) PRIMARY KEY NOT NULL,	
PHONE_NUMBER VARCHAR(50) NOT NULL,
CONTACT_PERSON VARCHAR(50) NOT NULL,
BUSINESS_TYPE VARCHAR(50) NOT NULL
);
	-- CREATE ASSOCIATED_STORES TABLE.
	CREATE TABLE ASSOCIATED_STORES (
	`NAME` VARCHAR(50) NOT NULL,	
	ASSOCIATED_STORE VARCHAR(50) NOT NULL,
    PRIMARY KEY(`NAME`, ASSOCIATED_STORE)
	);
    
-- CREATE GEOGRAPHICAL_LOCATION TABLE.
CREATE TABLE GEOGRAPHICAL_LOCATION (	
CITY_NAME VARCHAR(50) NOT NULL,
STATE_NAME VARCHAR(50) NOT NULL,
COUNTRY_NAME VARCHAR(50) NOT NULL,
ZIP_CODE INT NOT NULL,
PRIMARY KEY(CITY_NAME, STATE_NAME, COUNTRY_NAME, ZIP_CODE)
);

-- CREATE IMAGE TABLE.
CREATE TABLE IMAGE (
IMAGEID VARCHAR(50) PRIMARY KEY NOT NULL,
IMAGE_LINK VARCHAR(50) NOT NULL,
USERNAME VARCHAR(50) NOT NULL
);

-- CREATE TRIP_PLAN TABLE.
CREATE TABLE TRIP_PLAN (
PLANID	VARCHAR(50) PRIMARY KEY NOT NULL,
`NAME` VARCHAR (50) NOT NULL,
PURPOSE VARCHAR(265) NOT NULL,
START_DATE_TIME DATETIME NOT NULL,
END_DATE_TIME DATETIME NOT NULL,
USERNAME VARCHAR(50) NOT NULL,
POTENTIAL_COST DECIMAL(12,2) NOT NULL
);
	-- CREATE TRIP_PLAN_ATTRACTIONS TABLE.
	CREATE TABLE TRIP_PLAN_ATTRACTIONS (
	ATTRACTIONID VARCHAR(50) PRIMARY KEY,
    PLANID	VARCHAR(50) NOT NULL,
	ATTRACTION_NAME VARCHAR(50) NOT NULL
	);
    
    -- CREATE ASSOCIATED_MEMBERS TABLE.
    CREATE TABLE ASSOCIATED_MEMBERS (
	ASSOCIATED_MEMBER_ID VARCHAR(50) PRIMARY KEY,
    PLANID	VARCHAR(50) NOT NULL,
	ASSOCIATED_MEMBER_NAME VARCHAR(50) NOT NULL
	);
    
    -- CREATE DEPARTURE_DATE_TIMES TABLE.
    CREATE TABLE DEPARTURE_DATE_TIMES (
	DEPARTUREID VARCHAR(50) PRIMARY KEY,
    PLANID	VARCHAR(50) NOT NULL,
	DEPARTURE_DATE DATE NOT NULL,
    DEPARTURE_TIME TIME NOT NULL,
    DEPARTURE_LOCATION VARCHAR(50) NOT NULL
	);
    
    -- CREATE ARRIVAL_DATE_TIMES TABLE.
    CREATE TABLE ARRIVAL_DATE_TIMES (
	ARRIVALID VARCHAR(50) PRIMARY KEY,
    PLANID	VARCHAR(50) NOT NULL,
	ARRIVAL_DATE DATE NOT NULL,
	ARRIVAL_TIME TIME NOT NULL,
    ARRIVAL_LOCATION VARCHAR(50) NOT NULL
	);
    
    -- CREATE CONTAINS TABLE.
    CREATE TABLE `CONTAINS` (
	PLANID	VARCHAR(50) NOT NULL,
	`NAME` VARCHAR(50) NOT NULL,
	PHONE_NUMBER VARCHAR(50) NOT NULL,
    PRIMARY KEY(PLANID, `NAME`, PHONE_NUMBER)
	);
    
    -- CREATE RATES_PLAN_MEMBER TABLE.
    CREATE TABLE RATES_PLAN_MEMBER (
	PLANID VARCHAR(50) NOT NULL,	
	USERNAME VARCHAR(50) NOT NULL,
    RATING DECIMAL(3,1) NOT NULL,
    PRIMARY KEY(PLANID, USERNAME)
	);